# Generated by Django 4.2.4 on 2023-08-21 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
